/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 archer.glb 
Author: eon (https://sketchfab.com/facerate)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/elven-ranger-statue-71aec2d9f7724ae09992435ce8ff7258
Title: Elven ranger statue
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/archer.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials.material_0} />
        <mesh geometry={nodes.mesh_2.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/archer.glb')
