/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 factory-demo.01.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/factory-demo.01.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.地面.geometry} material={materials['材质.地面']} scale={6} />
      <mesh geometry={nodes.厂房1.geometry} material={materials['材质.厂房1']} position={[0, 1, -4]}>
        <mesh geometry={nodes.立柱1.geometry} material={materials['材质.立柱1']} position={[0, 1, 0]} scale={[0.322, 1, 0.304]} />
      </mesh>
      <mesh geometry={nodes.外立柱1.geometry} material={materials['材质.外立柱1']} position={[-4.191, 1, -1.921]} scale={[0.31, 1, 0.345]} />
    </group>
  )
}

useGLTF.preload('/factory-demo.01.glb')
