/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 monkey.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/monkey.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.猴头.geometry} material={materials['材质.001']} position={[0, 2.368, 0]} scale={2.203} />
      <mesh geometry={nodes.立方体.geometry} material={materials.材质} scale={[4, 0.2, 3.953]} />
    </group>
  )
}

useGLTF.preload('/monkey.glb')
