/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ybot.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ybot.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Y-Bot" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="YB_Body" geometry={nodes.YB_Body.geometry} material={materials.YB_Body} skeleton={nodes.YB_Body.skeleton} />
          <skinnedMesh name="YB_Joints" geometry={nodes.YB_Joints.geometry} material={materials.YB_Joints} skeleton={nodes.YB_Joints.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ybot.glb')
