/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jz.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import Indicator from '../Indicator'
import { CubeProps } from '../type'
import * as THREE from 'three'
import BimText3D from '../text/BimText3D'
import useHover from '../hooks/useHover'
import CubeInfoCard from '../card/CubeInfoCard'

type GLTFResult = GLTF & {
  nodes: { [key: string]: THREE.Mesh }
  materials: { [key: string]: THREE.MeshStandardMaterial }
}

export function Cube581({ ...props }: CubeProps) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)
  const { hovered, setHovered, onPointerOver, onPointerOut } = useHover()

  // 克隆材质以防止影响其他使用相同材质的对象
  const meshMaterial = materials.Color_M04.clone()
  const backMaterial = materials.BackColor.clone()

  // 设置发光效果
  if (hovered) {
    meshMaterial.emissive = new THREE.Color(0x666666)
    backMaterial.emissive = new THREE.Color(0x666666)
  } else {
    meshMaterial.emissive = new THREE.Color(0x000000)
    backMaterial.emissive = new THREE.Color(0x000000)
  }

  return (
    <group name="581" {...props} dispose={null}>
      <group
        ref={targetRef}
        name="Mesh581"
        position={[-15.494, 14.964, -19.706]}
        onPointerOver={onPointerOver}
        onPointerOut={onPointerOut}
      >
        <mesh name="Mesh581_1" geometry={nodes.Mesh581_1.geometry} material={meshMaterial} />
        <mesh name="Mesh581_2" geometry={nodes.Mesh581_2.geometry} material={backMaterial} />

        {/* 指示牌 */}

          <Indicator targetRef={targetRef} visible={hovered} name='581' orientPos={[-20, 0, 0]}>
            <CubeInfoCard
              no='581'
              name='③联C40砼上涵首墙身及顶板'
              status='已浇筑'
              temperature={30}
              onClose={() => setHovered(false)}
            />
          </Indicator>
        <BimText3D text="581" width={6} position={[-12.3, 0, -17]} rotation={[0, -Math.PI / 2, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
