/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cube419.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from '../Indicator'
import * as THREE from 'three'
import { CubeProps } from '../type'
import BimText3D from '../text/BimText3D'
import useHover from '../hooks/useHover'
import { Button } from 'antd'
import { CloseOutlined } from '@ant-design/icons'
import CubeInfoCard from '../card/CubeInfoCard'


export function Cube419({ ...props }: CubeProps) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)
  const { hovered, setHovered, onPointerOver, onPointerOut } = useHover()

  // 克隆材质以防止影响其他使用相同材质的对象
  const meshMaterial = materials.Color_M05.clone()

  // 设置发光效果
  if (hovered) {
    meshMaterial.emissive = new THREE.Color(0x666666)
  } else {
    meshMaterial.emissive = new THREE.Color(0x000000)
  }

  return (
    <group name="419" {...props} dispose={null}>
      {/* <group name="Mesh419" position={[-15.494, 33.843, 61.451]}> */}
      <group
        ref={targetRef}
        name="Mesh419"
        position={[-15.494, 33.843, 61.451]}
        onPointerOver={onPointerOver}
        onPointerOut={onPointerOut}
      >
        <mesh name="Mesh419_1" geometry={nodes.Mesh419_1.geometry} material={meshMaterial} />
        {/* <mesh name="Mesh419_2" geometry={nodes.Mesh419_2.geometry} material={backMaterial} /> */}

        {/* 指示牌 */}

          <Indicator targetRef={targetRef} visible={hovered} name='419'>
            <CubeInfoCard
              no='419'
              name='③联C40砼上涵首墙身及顶板'
              status='已浇筑'
              temperature={30}
              onClose={() => setHovered(false)}
            />
          </Indicator>
        <BimText3D text="419" width={6} position={[5, 0, 8]} />
        <BimText3D text="419" width={6} position={[-12.3, 0, 1]} rotation={[0, -Math.PI / 2, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
