/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cube425.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import Indicator from '../Indicator'
import { CubeProps } from '../type'
import * as THREE from 'three'
import BimText3D from '../text/BimText3D'
import useHover from '../hooks/useHover'
import CubeInfoCard from '../card/CubeInfoCard'


export function Cube425({ ...props }: CubeProps) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)
  const { hovered, setHovered, onPointerOver, onPointerOut } = useHover()

  // 克隆材质以防止影响其他使用相同材质的对象
  const meshMaterial = materials.Color_M05.clone()

  // 设置发光效果
  if (hovered) {
    meshMaterial.emissive = new THREE.Color(0x666666)
  } else {
    meshMaterial.emissive = new THREE.Color(0x000000)
  }

  return (
    <group name="425" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh425" position={[14.971, 16.2524, 57.9112]} onPointerOver={onPointerOver} onPointerOut={onPointerOut}>
        <mesh
          name="Mesh425"
          geometry={nodes.Mesh425.geometry}
          material={meshMaterial}
        />

        {/* 指示牌 */}

          <Indicator targetRef={targetRef} visible={hovered} name='425'>
            <CubeInfoCard
              no='425'
              name='③联C40砼上涵首墙身及顶板'
              status='已浇筑'
              temperature={30}
              onClose={() => setHovered(false)}
            />
          </Indicator>
        <BimText3D text="425" width={6} position={[5, 0, 12]} />
        <BimText3D text="425" width={6} position={[12.3, 0, 11]} rotation={[0, Math.PI / 2, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
