/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cube419.glb --keepgroups --keepnames 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cube419.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Scene_Collection">
          <group name="modal">
            <group name="419">
              <group name="Mesh419" position={[-15.494, 33.843, 61.451]}>
                <mesh name="Mesh169" geometry={nodes.Mesh169.geometry} material={materials.Color_M05} />
                <mesh name="Mesh169_1" geometry={nodes.Mesh169_1.geometry} material={materials.BackColor} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cube419.glb')
