/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jz.glb --keepgroups --keepnames
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/jz.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Scene_Collection">
          <group name="modal">
            <group name="417">
              <group name="pipe">
                <group name="Mesh5" position={[-15.369, 1.455, 70.069]}>
                  <mesh name="Mesh004" geometry={nodes.Mesh004.geometry} material={materials.FrontColor} />
                  <mesh name="Mesh004_1" geometry={nodes.Mesh004_1.geometry} material={materials.BackColor} />
                </group>
                <group name="Mesh6" position={[-15.411, 3.055, 68.044]}>
                  <mesh name="Mesh005" geometry={nodes.Mesh005.geometry} material={materials.FrontColor} />
                  <mesh name="Mesh005_1" geometry={nodes.Mesh005_1.geometry} material={materials.BackColor} />
                </group>
                <group name="Mesh7" position={[-15.369, 2.055, 63.569]}>
                  <mesh name="Mesh006" geometry={nodes.Mesh006.geometry} material={materials.FrontColor} />
                  <mesh name="Mesh006_1" geometry={nodes.Mesh006_1.geometry} material={materials.BackColor} />
                </group>
                <group name="Mesh8" position={[-15.369, 2.055, 67.144]}>
                  <mesh name="Mesh007" geometry={nodes.Mesh007.geometry} material={materials.FrontColor} />
                  <mesh name="Mesh007_1" geometry={nodes.Mesh007_1.geometry} material={materials.BackColor} />
                </group>
              </group>
              <mesh name="Mesh417" geometry={nodes.Mesh417.geometry} material={materials.Color_M04} position={[-15.494, 3.156, 62.43]} />
            </group>
            <group name="418">
              <mesh name="Mesh418" geometry={nodes.Mesh418.geometry} material={materials.Color_M05} position={[-15.429, 16.252, 57.911]} />
            </group>
            <group name="419" position={[-15, 34, 61]}>
              <group name="Mesh419">
                <mesh name="Mesh419_1" geometry={nodes.Mesh419_1.geometry} material={materials.Color_M05} />
                <mesh name="Mesh419_2" geometry={nodes.Mesh419_2.geometry} material={materials.BackColor} />
              </group>
            </group>
            <group name="424">
              <group name="pipe001">
                <group name="Mesh10" position={[15.031, 1.455, 70.069]}>
                  <mesh name="Mesh009" geometry={nodes.Mesh009.geometry} material={materials.FrontColor} />
                  <mesh name="Mesh009_1" geometry={nodes.Mesh009_1.geometry} material={materials.BackColor} />
                </group>
                <group name="Mesh11" position={[14.989, 3.055, 68.044]}>
                  <mesh name="Mesh010" geometry={nodes.Mesh010.geometry} material={materials.FrontColor} />
                  <mesh name="Mesh010_1" geometry={nodes.Mesh010_1.geometry} material={materials.BackColor} />
                </group>
                <group name="Mesh12" position={[15.031, 2.055, 63.569]}>
                  <mesh name="Mesh011" geometry={nodes.Mesh011.geometry} material={materials.FrontColor} />
                  <mesh name="Mesh011_1" geometry={nodes.Mesh011_1.geometry} material={materials.BackColor} />
                </group>
                <group name="Mesh13" position={[15.031, 2.055, 67.144]}>
                  <mesh name="Mesh012" geometry={nodes.Mesh012.geometry} material={materials.FrontColor} />
                  <mesh name="Mesh012_1" geometry={nodes.Mesh012_1.geometry} material={materials.BackColor} />
                </group>
              </group>
              <mesh name="Mesh424" geometry={nodes.Mesh424.geometry} material={materials.Color_M04} position={[14.906, 3.156, 62.43]} />
            </group>
            <group name="425">
              <mesh name="Mesh425" geometry={nodes.Mesh425.geometry} material={materials.Color_M05} position={[14.971, 16.252, 57.911]} />
            </group>
            <group name="426">
              <group name="Mesh426" position={[14.906, 33.771, 61.731]}>
                <mesh name="Mesh426_1" geometry={nodes.Mesh426_1.geometry} material={materials.Color_M05} />
                <mesh name="Mesh426_2" geometry={nodes.Mesh426_2.geometry} material={materials.BackColor} />
              </group>
            </group>
            <group name="498">
              <group name="pipe002">
                <group name="Mesh29" position={[-15.369, 1.455, -69.481]}>
                  <mesh name="Mesh028" geometry={nodes.Mesh028.geometry} material={materials.FrontColor} />
                  <mesh name="Mesh028_1" geometry={nodes.Mesh028_1.geometry} material={materials.BackColor} />
                </group>
                <group name="Mesh30" position={[-15.411, 3.055, -67.456]}>
                  <mesh name="Mesh029" geometry={nodes.Mesh029.geometry} material={materials.FrontColor} />
                  <mesh name="Mesh029_1" geometry={nodes.Mesh029_1.geometry} material={materials.BackColor} />
                </group>
                <group name="Mesh31" position={[-15.369, 2.055, -62.981]}>
                  <mesh name="Mesh030" geometry={nodes.Mesh030.geometry} material={materials.FrontColor} />
                  <mesh name="Mesh030_1" geometry={nodes.Mesh030_1.geometry} material={materials.BackColor} />
                </group>
                <group name="Mesh32" position={[-15.369, 2.055, -66.556]}>
                  <mesh name="Mesh031" geometry={nodes.Mesh031.geometry} material={materials.FrontColor} />
                  <mesh name="Mesh031_1" geometry={nodes.Mesh031_1.geometry} material={materials.BackColor} />
                </group>
              </group>
              <mesh name="Mesh498" geometry={nodes.Mesh498.geometry} material={materials.Color_M00} position={[-15.494, 3.156, -61.843]} />
            </group>
            <group name="499">
              <group name="Mesh4991" position={[-15.494, 16.088, -62.293]}>
                <mesh name="Mesh4991_1" geometry={nodes.Mesh4991_1.geometry} material={materials.Color_M05} />
                <mesh name="Mesh4991_2" geometry={nodes.Mesh4991_2.geometry} material={materials.BackColor} />
              </group>
              <group name="Mesh4992" position={[-15.494, 15.722, -49.877]}>
                <mesh name="Mesh4992_1" geometry={nodes.Mesh4992_1.geometry} material={materials.Color_M05} />
                <mesh name="Mesh4992_2" geometry={nodes.Mesh4992_2.geometry} material={materials.BackColor} />
              </group>
            </group>
            <group name="505">
              <group name="pipe003">
                <group name="Mesh24" position={[15.031, 1.455, -69.481]}>
                  <mesh name="Mesh023" geometry={nodes.Mesh023.geometry} material={materials.FrontColor} />
                  <mesh name="Mesh023_1" geometry={nodes.Mesh023_1.geometry} material={materials.BackColor} />
                </group>
                <group name="Mesh25" position={[14.989, 3.055, -67.456]}>
                  <mesh name="Mesh024" geometry={nodes.Mesh024.geometry} material={materials.FrontColor} />
                  <mesh name="Mesh024_1" geometry={nodes.Mesh024_1.geometry} material={materials.BackColor} />
                </group>
                <group name="Mesh26" position={[15.031, 2.055, -62.981]}>
                  <mesh name="Mesh025" geometry={nodes.Mesh025.geometry} material={materials.FrontColor} />
                  <mesh name="Mesh025_1" geometry={nodes.Mesh025_1.geometry} material={materials.BackColor} />
                </group>
                <group name="Mesh27" position={[15.031, 2.055, -66.556]}>
                  <mesh name="Mesh026" geometry={nodes.Mesh026.geometry} material={materials.FrontColor} />
                  <mesh name="Mesh026_1" geometry={nodes.Mesh026_1.geometry} material={materials.BackColor} />
                </group>
              </group>
              <mesh name="Mesh505" geometry={nodes.Mesh505.geometry} material={materials.Color_M04} position={[14.906, 3.156, -61.843]} />
            </group>
            <group name="506">
              <group name="Mesh5061" position={[14.906, 16.088, -62.293]}>
                <mesh name="Mesh5061_1" geometry={nodes.Mesh5061_1.geometry} material={materials.Color_M05} />
                <mesh name="Mesh5061_2" geometry={nodes.Mesh5061_2.geometry} material={materials.BackColor} />
              </group>
              <group name="Mesh5062" position={[14.906, 15.722, -49.877]}>
                <mesh name="Mesh5062_1" geometry={nodes.Mesh5062_1.geometry} material={materials.Color_M05} />
                <mesh name="Mesh5062_2" geometry={nodes.Mesh5062_2.geometry} material={materials.BackColor} />
              </group>
            </group>
            <group name="577">
              <group name="Mesh577" position={[-15.494, 2.647, 20.294]}>
                <mesh name="Mesh577_1" geometry={nodes.Mesh577_1.geometry} material={materials.Color_M00} />
                <mesh name="Mesh577_2" geometry={nodes.Mesh577_2.geometry} material={materials.BackColor} />
              </group>
            </group>
            <group name="578">
              <group name="Monitor5781">
                <group name="Group127">
                  <group name="Group128">
                    <mesh name="Mesh134" geometry={nodes.Mesh134.geometry} material={materials._31} position={[-27.194, 17.605, 20.301]} />
                  </group>
                  <group name="Group129">
                    <group name="Mesh135" position={[-27.144, 12.055, 20.294]}>
                      <mesh name="Mesh134_1" geometry={nodes.Mesh134_1.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh134_2" geometry={nodes.Mesh134_2.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group130">
                    <mesh name="Mesh136" geometry={nodes.Mesh136.geometry} material={materials._31} position={[-26.815, 15.655, 20.305]} />
                  </group>
                  <group name="Group131">
                    <mesh name="Mesh137" geometry={nodes.Mesh137.geometry} material={materials._31} position={[-27.194, 14.877, 20.301]} />
                  </group>
                  <group name="Group132">
                    <mesh name="Mesh138" geometry={nodes.Mesh138.geometry} material={materials._31} position={[-26.815, 12.055, 20.304]} />
                  </group>
                  <group name="Group133">
                    <mesh name="Mesh139" geometry={nodes.Mesh139.geometry} material={materials._31} position={[-27.195, 11.755, 20.302]} />
                  </group>
                  <group name="Group134">
                    <mesh name="Mesh140" geometry={nodes.Mesh140.geometry} material={materials._31} position={[-27.573, 12.055, 20.302]} />
                  </group>
                  <group name="Group135">
                    <group name="Mesh141" position={[-27.244, 12.055, 20.294]}>
                      <mesh name="Mesh140_1" geometry={nodes.Mesh140_1.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh140_2" geometry={nodes.Mesh140_2.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group136">
                    <group name="Mesh142" position={[-27.144, 15.655, 20.294]}>
                      <mesh name="Mesh141_1" geometry={nodes.Mesh141_1.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh141_2" geometry={nodes.Mesh141_2.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group137">
                    <group name="Mesh143" position={[-27.244, 15.655, 20.294]}>
                      <mesh name="Mesh142_1" geometry={nodes.Mesh142_1.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh142_2" geometry={nodes.Mesh142_2.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group138">
                    <mesh name="Mesh144" geometry={nodes.Mesh144.geometry} material={materials._31} position={[-27.572, 15.655, 20.301]} />
                  </group>
                </group>
                <group name="Group139">
                  <mesh name="Mesh145" geometry={nodes.Mesh145.geometry} material={materials.Color_G04} position={[-32.113, 17.899, 17.142]} />
                </group>
                <group name="Group140">
                  <group name="Group141">
                    <mesh name="Mesh146" geometry={nodes.Mesh146.geometry} material={materials._31} position={[-19.393, 17.605, 20.301]} />
                  </group>
                  <group name="Group142">
                    <group name="Mesh147" position={[-19.344, 12.055, 20.294]}>
                      <mesh name="Mesh146_1" geometry={nodes.Mesh146_1.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh146_2" geometry={nodes.Mesh146_2.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group143">
                    <mesh name="Mesh148" geometry={nodes.Mesh148.geometry} material={materials._31} position={[-19.015, 15.655, 20.305]} />
                  </group>
                  <group name="Group144">
                    <mesh name="Mesh149" geometry={nodes.Mesh149.geometry} material={materials._31} position={[-19.393, 14.877, 20.301]} />
                  </group>
                  <group name="Group145">
                    <mesh name="Mesh150" geometry={nodes.Mesh150.geometry} material={materials._31} position={[-19.015, 12.055, 20.304]} />
                  </group>
                  <group name="Group146">
                    <mesh name="Mesh151" geometry={nodes.Mesh151.geometry} material={materials._31} position={[-19.395, 11.755, 20.302]} />
                  </group>
                  <group name="Group147">
                    <mesh name="Mesh152" geometry={nodes.Mesh152.geometry} material={materials._31} position={[-19.773, 12.055, 20.302]} />
                  </group>
                  <group name="Group148">
                    <group name="Mesh153" position={[-19.444, 12.055, 20.294]}>
                      <mesh name="Mesh152_1" geometry={nodes.Mesh152_1.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh152_2" geometry={nodes.Mesh152_2.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group149">
                    <group name="Mesh154" position={[-19.344, 15.655, 20.294]}>
                      <mesh name="Mesh153_1" geometry={nodes.Mesh153_1.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh153_2" geometry={nodes.Mesh153_2.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group150">
                    <group name="Mesh155" position={[-19.444, 15.655, 20.294]}>
                      <mesh name="Mesh154_1" geometry={nodes.Mesh154_1.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh154_2" geometry={nodes.Mesh154_2.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group151">
                    <mesh name="Mesh156" geometry={nodes.Mesh156.geometry} material={materials._31} position={[-19.772, 15.655, 20.301]} />
                  </group>
                </group>
              </group>
              <group name="Monitor5782">
                <group name="Group153">
                  <group name="Mesh157" position={[-27.344, 11.155, 37.294]}>
                    <mesh name="Mesh156_1" geometry={nodes.Mesh156_1.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh156_2" geometry={nodes.Mesh156_2.geometry} material={materials.BackColor} />
                  </group>
                  <group name="Mesh158" position={[-27.044, 11.155, 37.294]}>
                    <mesh name="Mesh157_1" geometry={nodes.Mesh157_1.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh157_2" geometry={nodes.Mesh157_2.geometry} material={materials.BackColor} />
                  </group>
                </group>
                <group name="Group154">
                  <group name="Mesh159" position={[-11.744, 11.155, 37.294]}>
                    <mesh name="Mesh158_1" geometry={nodes.Mesh158_1.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh158_2" geometry={nodes.Mesh158_2.geometry} material={materials.BackColor} />
                  </group>
                  <group name="Mesh160" position={[-11.444, 11.155, 37.294]}>
                    <mesh name="Mesh159_1" geometry={nodes.Mesh159_1.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh159_2" geometry={nodes.Mesh159_2.geometry} material={materials.BackColor} />
                  </group>
                </group>
                <group name="Group155">
                  <group name="Mesh161" position={[-3.944, 11.155, 37.294]}>
                    <mesh name="Mesh160_1" geometry={nodes.Mesh160_1.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh160_2" geometry={nodes.Mesh160_2.geometry} material={materials.BackColor} />
                  </group>
                  <group name="Mesh162" position={[-3.644, 11.155, 37.294]}>
                    <mesh name="Mesh161_1" geometry={nodes.Mesh161_1.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh161_2" geometry={nodes.Mesh161_2.geometry} material={materials.BackColor} />
                  </group>
                </group>
                <group name="Group156">
                  <group name="Mesh163" position={[-19.544, 11.155, 37.294]}>
                    <mesh name="Mesh162_1" geometry={nodes.Mesh162_1.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh162_2" geometry={nodes.Mesh162_2.geometry} material={materials.BackColor} />
                  </group>
                  <group name="Mesh164" position={[-19.244, 11.155, 37.294]}>
                    <mesh name="Mesh163_1" geometry={nodes.Mesh163_1.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh163_2" geometry={nodes.Mesh163_2.geometry} material={materials.BackColor} />
                  </group>
                </group>
              </group>
              <group name="Mesh578" position={[-15.494, 14.964, 20.294]}>
                <mesh name="Mesh578_1" geometry={nodes.Mesh578_1.geometry} material={materials.Color_M04} />
                <mesh name="Mesh578_2" geometry={nodes.Mesh578_2.geometry} material={materials.BackColor} />
              </group>
            </group>
            <group name="580">
              <group name="Mesh580" position={[-15.494, 2.647, -19.706]}>
                <mesh name="Mesh580_1" geometry={nodes.Mesh580_1.geometry} material={materials.Color_M04} />
                <mesh name="Mesh580_2" geometry={nodes.Mesh580_2.geometry} material={materials.BackColor} />
              </group>
            </group>
            <group name="581">
              <group name="Monitor581">
                <group name="Group120">
                  <group name="Mesh125" position={[-27.344, 11.155, -2.706]}>
                    <mesh name="Mesh124" geometry={nodes.Mesh124.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh124_1" geometry={nodes.Mesh124_1.geometry} material={materials.BackColor} />
                  </group>
                  <group name="Mesh126" position={[-27.044, 11.155, -2.706]}>
                    <mesh name="Mesh125_1" geometry={nodes.Mesh125_1.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh125_2" geometry={nodes.Mesh125_2.geometry} material={materials.BackColor} />
                  </group>
                </group>
                <group name="Group121">
                  <group name="Mesh127" position={[-11.744, 11.155, -2.706]}>
                    <mesh name="Mesh126_1" geometry={nodes.Mesh126_1.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh126_2" geometry={nodes.Mesh126_2.geometry} material={materials.BackColor} />
                  </group>
                  <group name="Mesh128" position={[-11.444, 11.155, -2.706]}>
                    <mesh name="Mesh127_1" geometry={nodes.Mesh127_1.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh127_2" geometry={nodes.Mesh127_2.geometry} material={materials.BackColor} />
                  </group>
                </group>
                <group name="Group122">
                  <group name="Mesh129" position={[-3.944, 11.155, -2.706]}>
                    <mesh name="Mesh128_1" geometry={nodes.Mesh128_1.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh128_2" geometry={nodes.Mesh128_2.geometry} material={materials.BackColor} />
                  </group>
                  <group name="Mesh130" position={[-3.644, 11.155, -2.706]}>
                    <mesh name="Mesh129_1" geometry={nodes.Mesh129_1.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh129_2" geometry={nodes.Mesh129_2.geometry} material={materials.BackColor} />
                  </group>
                </group>
                <group name="Group123">
                  <group name="Mesh131" position={[-19.544, 11.155, -2.706]}>
                    <mesh name="Mesh130_1" geometry={nodes.Mesh130_1.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh130_2" geometry={nodes.Mesh130_2.geometry} material={materials.BackColor} />
                  </group>
                  <group name="Mesh132" position={[-19.244, 11.155, -2.706]}>
                    <mesh name="Mesh131_1" geometry={nodes.Mesh131_1.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh131_2" geometry={nodes.Mesh131_2.geometry} material={materials.BackColor} />
                  </group>
                </group>
              </group>
              <group name="Mesh581" position={[-15.494, 14.964, -19.706]}>
                <mesh name="Mesh581_1" geometry={nodes.Mesh581_1.geometry} material={materials.Color_M04} />
                <mesh name="Mesh581_2" geometry={nodes.Mesh581_2.geometry} material={materials.BackColor} />
              </group>
            </group>
            <group name="583">
              <group name="Mesh583" position={[14.906, 2.647, 20.294]}>
                <mesh name="Mesh583_1" geometry={nodes.Mesh583_1.geometry} material={materials.Color_M04} />
                <mesh name="Mesh583_2" geometry={nodes.Mesh583_2.geometry} material={materials.BackColor} />
              </group>
            </group>
            <group name="584">
              <group name="Monitor5841">
                <group name="Group28">
                  <group name="Group29">
                    <mesh name="Mesh38" geometry={nodes.Mesh38.geometry} material={materials._31} position={[3.206, 17.605, 20.301]} />
                  </group>
                  <group name="Group30">
                    <group name="Mesh39" position={[3.256, 12.055, 20.294]}>
                      <mesh name="Mesh038" geometry={nodes.Mesh038.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh038_1" geometry={nodes.Mesh038_1.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group31">
                    <mesh name="Mesh40" geometry={nodes.Mesh40.geometry} material={materials._31} position={[3.585, 15.655, 20.305]} />
                  </group>
                  <group name="Group32">
                    <mesh name="Mesh41" geometry={nodes.Mesh41.geometry} material={materials._31} position={[3.206, 14.877, 20.301]} />
                  </group>
                  <group name="Group33">
                    <mesh name="Mesh42" geometry={nodes.Mesh42.geometry} material={materials._31} position={[3.585, 12.055, 20.304]} />
                  </group>
                  <group name="Group34">
                    <mesh name="Mesh43" geometry={nodes.Mesh43.geometry} material={materials._31} position={[3.205, 11.755, 20.302]} />
                  </group>
                  <group name="Group35">
                    <mesh name="Mesh44" geometry={nodes.Mesh44.geometry} material={materials._31} position={[2.827, 12.055, 20.302]} />
                  </group>
                  <group name="Group36">
                    <group name="Mesh45" position={[3.156, 12.055, 20.294]}>
                      <mesh name="Mesh044" geometry={nodes.Mesh044.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh044_1" geometry={nodes.Mesh044_1.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group37">
                    <group name="Mesh46" position={[3.256, 15.655, 20.294]}>
                      <mesh name="Mesh045" geometry={nodes.Mesh045.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh045_1" geometry={nodes.Mesh045_1.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group38">
                    <group name="Mesh47" position={[3.156, 15.655, 20.294]}>
                      <mesh name="Mesh046" geometry={nodes.Mesh046.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh046_1" geometry={nodes.Mesh046_1.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group39">
                    <mesh name="Mesh48" geometry={nodes.Mesh48.geometry} material={materials._31} position={[2.828, 15.655, 20.301]} />
                  </group>
                </group>
                <group name="Group40">
                  <mesh name="Mesh49" geometry={nodes.Mesh49.geometry} material={materials.Color_G04} position={[-1.713, 17.899, 17.142]} />
                </group>
                <group name="Group41">
                  <group name="Group42">
                    <mesh name="Mesh50" geometry={nodes.Mesh50.geometry} material={materials._31} position={[11.006, 17.605, 20.301]} />
                  </group>
                  <group name="Group43">
                    <group name="Mesh51" position={[11.056, 12.055, 20.294]}>
                      <mesh name="Mesh050" geometry={nodes.Mesh050.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh050_1" geometry={nodes.Mesh050_1.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group44">
                    <mesh name="Mesh52" geometry={nodes.Mesh52.geometry} material={materials._31} position={[11.385, 15.655, 20.305]} />
                  </group>
                  <group name="Group45">
                    <mesh name="Mesh53" geometry={nodes.Mesh53.geometry} material={materials._31} position={[11.006, 14.877, 20.301]} />
                  </group>
                  <group name="Group46">
                    <mesh name="Mesh54" geometry={nodes.Mesh54.geometry} material={materials._31} position={[11.385, 12.055, 20.304]} />
                  </group>
                  <group name="Group47">
                    <mesh name="Mesh55" geometry={nodes.Mesh55.geometry} material={materials._31} position={[11.005, 11.755, 20.302]} />
                  </group>
                  <group name="Group48">
                    <mesh name="Mesh56" geometry={nodes.Mesh56.geometry} material={materials._31} position={[10.627, 12.055, 20.302]} />
                  </group>
                  <group name="Group49">
                    <group name="Mesh57" position={[10.956, 12.055, 20.294]}>
                      <mesh name="Mesh056" geometry={nodes.Mesh056.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh056_1" geometry={nodes.Mesh056_1.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group50">
                    <group name="Mesh58" position={[11.056, 15.655, 20.294]}>
                      <mesh name="Mesh057" geometry={nodes.Mesh057.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh057_1" geometry={nodes.Mesh057_1.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group51">
                    <group name="Mesh59" position={[10.956, 15.655, 20.294]}>
                      <mesh name="Mesh058" geometry={nodes.Mesh058.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh058_1" geometry={nodes.Mesh058_1.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group52">
                    <mesh name="Mesh60" geometry={nodes.Mesh60.geometry} material={materials._31} position={[10.628, 15.655, 20.301]} />
                  </group>
                </group>
              </group>
              <group name="Monitor5842">
                <group name="Group54">
                  <group name="Mesh61" position={[3.056, 11.155, 37.294]}>
                    <mesh name="Mesh060" geometry={nodes.Mesh060.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh060_1" geometry={nodes.Mesh060_1.geometry} material={materials.BackColor} />
                  </group>
                  <group name="Mesh62" position={[3.356, 11.155, 37.294]}>
                    <mesh name="Mesh061" geometry={nodes.Mesh061.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh061_1" geometry={nodes.Mesh061_1.geometry} material={materials.BackColor} />
                  </group>
                </group>
                <group name="Group55">
                  <group name="Mesh63" position={[18.656, 11.155, 37.294]}>
                    <mesh name="Mesh062" geometry={nodes.Mesh062.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh062_1" geometry={nodes.Mesh062_1.geometry} material={materials.BackColor} />
                  </group>
                  <group name="Mesh64" position={[18.956, 11.155, 37.294]}>
                    <mesh name="Mesh063" geometry={nodes.Mesh063.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh063_1" geometry={nodes.Mesh063_1.geometry} material={materials.BackColor} />
                  </group>
                </group>
                <group name="Group56">
                  <group name="Mesh65" position={[26.456, 11.155, 37.294]}>
                    <mesh name="Mesh064" geometry={nodes.Mesh064.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh064_1" geometry={nodes.Mesh064_1.geometry} material={materials.BackColor} />
                  </group>
                  <group name="Mesh66" position={[26.756, 11.155, 37.294]}>
                    <mesh name="Mesh065" geometry={nodes.Mesh065.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh065_1" geometry={nodes.Mesh065_1.geometry} material={materials.BackColor} />
                  </group>
                </group>
                <group name="Group57">
                  <group name="Mesh67" position={[10.856, 11.155, 37.294]}>
                    <mesh name="Mesh066" geometry={nodes.Mesh066.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh066_1" geometry={nodes.Mesh066_1.geometry} material={materials.BackColor} />
                  </group>
                  <group name="Mesh68" position={[11.156, 11.155, 37.294]}>
                    <mesh name="Mesh067" geometry={nodes.Mesh067.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh067_1" geometry={nodes.Mesh067_1.geometry} material={materials.BackColor} />
                  </group>
                </group>
              </group>
              <group name="Mesh584" position={[14.906, 14.964, 20.294]}>
                <mesh name="Mesh584_1" geometry={nodes.Mesh584_1.geometry} material={materials.Color_M04} />
                <mesh name="Mesh584_2" geometry={nodes.Mesh584_2.geometry} material={materials.BackColor} />
              </group>
            </group>
            <group name="586">
              <group name="Mesh586" position={[14.906, 2.647, -19.706]}>
                <mesh name="Mesh586_1" geometry={nodes.Mesh586_1.geometry} material={materials.Color_M00} />
                <mesh name="Mesh586_2" geometry={nodes.Mesh586_2.geometry} material={materials.BackColor} />
              </group>
            </group>
            <group name="587">
              <group name="Monitor5871">
                <group name="Group61">
                  <group name="Group62">
                    <mesh name="Mesh70" geometry={nodes.Mesh70.geometry} material={materials._31} position={[3.206, 17.605, -19.699]} />
                  </group>
                  <group name="Group63">
                    <group name="Mesh71" position={[3.256, 12.055, -19.706]}>
                      <mesh name="Mesh070" geometry={nodes.Mesh070.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh070_1" geometry={nodes.Mesh070_1.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group64">
                    <mesh name="Mesh72" geometry={nodes.Mesh72.geometry} material={materials._31} position={[3.585, 15.655, -19.695]} />
                  </group>
                  <group name="Group65">
                    <mesh name="Mesh73" geometry={nodes.Mesh73.geometry} material={materials._31} position={[3.206, 14.877, -19.699]} />
                  </group>
                  <group name="Group66">
                    <mesh name="Mesh74" geometry={nodes.Mesh74.geometry} material={materials._31} position={[3.585, 12.055, -19.696]} />
                  </group>
                  <group name="Group67">
                    <mesh name="Mesh75" geometry={nodes.Mesh75.geometry} material={materials._31} position={[3.205, 11.755, -19.698]} />
                  </group>
                  <group name="Group68">
                    <mesh name="Mesh76" geometry={nodes.Mesh76.geometry} material={materials._31} position={[2.827, 12.055, -19.698]} />
                  </group>
                  <group name="Group69">
                    <group name="Mesh77" position={[3.156, 12.055, -19.706]}>
                      <mesh name="Mesh076" geometry={nodes.Mesh076.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh076_1" geometry={nodes.Mesh076_1.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group70">
                    <group name="Mesh78" position={[3.256, 15.655, -19.706]}>
                      <mesh name="Mesh077" geometry={nodes.Mesh077.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh077_1" geometry={nodes.Mesh077_1.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group71">
                    <group name="Mesh79" position={[3.156, 15.655, -19.706]}>
                      <mesh name="Mesh078" geometry={nodes.Mesh078.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh078_1" geometry={nodes.Mesh078_1.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group72">
                    <mesh name="Mesh80" geometry={nodes.Mesh80.geometry} material={materials._31} position={[2.828, 15.655, -19.699]} />
                  </group>
                </group>
                <group name="Group73">
                  <mesh name="Mesh81" geometry={nodes.Mesh81.geometry} material={materials.Color_G04} position={[-1.713, 17.899, -22.858]} />
                </group>
                <group name="Group74">
                  <group name="Group75">
                    <mesh name="Mesh82" geometry={nodes.Mesh82.geometry} material={materials._31} position={[11.006, 17.605, -19.699]} />
                  </group>
                  <group name="Group76">
                    <group name="Mesh83" position={[11.056, 12.055, -19.706]}>
                      <mesh name="Mesh082" geometry={nodes.Mesh082.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh082_1" geometry={nodes.Mesh082_1.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group77">
                    <mesh name="Mesh84" geometry={nodes.Mesh84.geometry} material={materials._31} position={[11.385, 15.655, -19.695]} />
                  </group>
                  <group name="Group78">
                    <mesh name="Mesh85" geometry={nodes.Mesh85.geometry} material={materials._31} position={[11.006, 14.877, -19.699]} />
                  </group>
                  <group name="Group79">
                    <mesh name="Mesh86" geometry={nodes.Mesh86.geometry} material={materials._31} position={[11.385, 12.055, -19.696]} />
                  </group>
                  <group name="Group80">
                    <mesh name="Mesh87" geometry={nodes.Mesh87.geometry} material={materials._31} position={[11.005, 11.755, -19.698]} />
                  </group>
                  <group name="Group81">
                    <mesh name="Mesh88" geometry={nodes.Mesh88.geometry} material={materials._31} position={[10.627, 12.055, -19.698]} />
                  </group>
                  <group name="Group82">
                    <group name="Mesh89" position={[10.956, 12.055, -19.706]}>
                      <mesh name="Mesh088" geometry={nodes.Mesh088.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh088_1" geometry={nodes.Mesh088_1.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group83">
                    <group name="Mesh90" position={[11.056, 15.655, -19.706]}>
                      <mesh name="Mesh089" geometry={nodes.Mesh089.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh089_1" geometry={nodes.Mesh089_1.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group84">
                    <group name="Mesh91" position={[10.956, 15.655, -19.706]}>
                      <mesh name="Mesh090" geometry={nodes.Mesh090.geometry} material={materials.Color_A05} />
                      <mesh name="Mesh090_1" geometry={nodes.Mesh090_1.geometry} material={materials.BackColor} />
                    </group>
                  </group>
                  <group name="Group85">
                    <mesh name="Mesh92" geometry={nodes.Mesh92.geometry} material={materials._31} position={[10.628, 15.655, -19.699]} />
                  </group>
                </group>
              </group>
              <group name="Monitor5872">
                <group name="Group87">
                  <group name="Mesh93" position={[3.056, 11.155, -2.706]}>
                    <mesh name="Mesh092" geometry={nodes.Mesh092.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh092_1" geometry={nodes.Mesh092_1.geometry} material={materials.BackColor} />
                  </group>
                  <group name="Mesh94" position={[3.356, 11.155, -2.706]}>
                    <mesh name="Mesh093" geometry={nodes.Mesh093.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh093_1" geometry={nodes.Mesh093_1.geometry} material={materials.BackColor} />
                  </group>
                </group>
                <group name="Group88">
                  <group name="Mesh95" position={[18.656, 11.155, -2.706]}>
                    <mesh name="Mesh094" geometry={nodes.Mesh094.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh094_1" geometry={nodes.Mesh094_1.geometry} material={materials.BackColor} />
                  </group>
                  <group name="Mesh96" position={[18.956, 11.155, -2.706]}>
                    <mesh name="Mesh095" geometry={nodes.Mesh095.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh095_1" geometry={nodes.Mesh095_1.geometry} material={materials.BackColor} />
                  </group>
                </group>
                <group name="Group89">
                  <group name="Mesh97" position={[26.456, 11.155, -2.706]}>
                    <mesh name="Mesh096" geometry={nodes.Mesh096.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh096_1" geometry={nodes.Mesh096_1.geometry} material={materials.BackColor} />
                  </group>
                  <group name="Mesh98" position={[26.756, 11.155, -2.706]}>
                    <mesh name="Mesh097" geometry={nodes.Mesh097.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh097_1" geometry={nodes.Mesh097_1.geometry} material={materials.BackColor} />
                  </group>
                </group>
                <group name="Group90">
                  <group name="Mesh100" position={[11.156, 11.155, -2.706]}>
                    <mesh name="Mesh099" geometry={nodes.Mesh099.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh099_1" geometry={nodes.Mesh099_1.geometry} material={materials.BackColor} />
                  </group>
                  <group name="Mesh99" position={[10.856, 11.155, -2.706]}>
                    <mesh name="Mesh098" geometry={nodes.Mesh098.geometry} material={materials.FrontColor} />
                    <mesh name="Mesh098_1" geometry={nodes.Mesh098_1.geometry} material={materials.BackColor} />
                  </group>
                </group>
              </group>
              <group name="Mesh587" position={[14.906, 14.964, -19.706]}>
                <mesh name="Mesh587_1" geometry={nodes.Mesh587_1.geometry} material={materials.Color_M04} />
                <mesh name="Mesh587_2" geometry={nodes.Mesh587_2.geometry} material={materials.BackColor} />
              </group>
            </group>
            <group name="507">
              <mesh name="Mesh507" geometry={nodes.Mesh507.geometry} material={materials.Color_M05} position={[14.906, 34.884, -61.16]} />
            </group>
            <group name="500">
              <mesh name="Mesh500" geometry={nodes.Mesh500.geometry} material={materials['Color_M05.001']} position={[-15.494, 34.884, -61.16]} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/jz.glb')
