/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jz.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from './Indicator'
import { CubeProps } from './type'

export function Cube499({ ...props }: CubeProps) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="499" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh4991" position={[-15.494, 16.088, -62.293]}>
        <mesh name="Mesh4991_1" geometry={nodes.Mesh4991_1.geometry} material={materials.Color_M05} />
        <mesh name="Mesh4991_2" geometry={nodes.Mesh4991_2.geometry} material={materials.BackColor} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} name='499' orientPos={[0,0,-20]} />
      </group>
      <group name="Mesh4992" position={[-15.494, 15.722, -49.877]}>
        <mesh name="Mesh4992_1" geometry={nodes.Mesh4992_1.geometry} material={materials.Color_M05} />
        <mesh name="Mesh4992_2" geometry={nodes.Mesh4992_2.geometry} material={materials.BackColor} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
