/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jz.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from './Indicator'

export function Cube583(props) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="583" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh583" position={[14.906, 2.647, 20.294]}>
        <mesh name="Mesh583_1" geometry={nodes.Mesh583_1.geometry} material={materials.Color_M04} />
        <mesh name="Mesh583_2" geometry={nodes.Mesh583_2.geometry} material={materials.BackColor} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} name='583' orientPos={[20,0,0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
