/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jz.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from './Indicator'

export function Cube581(props) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="581" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh581" position={[-15.494, 14.964, -19.706]}>
        <mesh name="Mesh581_1" geometry={nodes.Mesh581_1.geometry} material={materials.Color_M04} />
        <mesh name="Mesh581_2" geometry={nodes.Mesh581_2.geometry} material={materials.BackColor} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} name='581' orientPos={[-30,0,0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
