/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cube419.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from './Indicator'

export function Cube419(props) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/cube419.glb')
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="419" {...props} dispose={null}>
      {/* <group name="Mesh419" position={[-15.494, 33.843, 61.451]}> */}
      <group ref={targetRef} name="Mesh419" position={[-15.494, 33.843, 61.451]}>
        <mesh name="Mesh169" geometry={nodes.Mesh169.geometry} material={materials.Color_M05} />
        <mesh name="Mesh169_1" geometry={nodes.Mesh169_1.geometry} material={materials.BackColor} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/cube419.glb')
