/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cube425.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from './Indicator'

export function Cube425(props) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="425" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh425" position={[14.971, 16.2524, 57.9112]}>
        <mesh name="Mesh425" geometry={nodes.Mesh425.geometry} material={materials.Color_M05} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} name='425' />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
