/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cube577.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from './Indicator'
import { CubeProps } from './type'

export function Cube577({ ...props }: CubeProps) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="577" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh577" position={[-15.494, 2.647, 20.294]}>
        <mesh name="Mesh577_1" geometry={nodes.Mesh577_1.geometry} material={materials.Color_M00} />
        <mesh name="Mesh577_2" geometry={nodes.Mesh577_2.geometry} material={materials.BackColor} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} name='577' orientPos={[-30,0,0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
