/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cube425.glb --keepgroups --keepnames
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import Indicator from './Indicator'
import { CubeProps } from './type'
import * as THREE from 'three'
import BimText3D from './text/BimText3D'

type GLTFResult = GLTF & {
  nodes: { [key: string]: THREE.Mesh }
  materials: { [key: string]: THREE.MeshStandardMaterial }
}

export function Cube425({ ...props }: CubeProps) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb') as GLTFResult
  const targetRef = useRef<THREE.Group>(null!)
  const [hovered, setHovered] = useState(false)

  // 克隆材质以防止影响其他使用相同材质的对象
  const meshMaterial = materials.Color_M05.clone()

  // 设置发光效果
  if (hovered) {
    meshMaterial.emissive = new THREE.Color(0x666666)
  } else {
    meshMaterial.emissive = new THREE.Color(0x000000)
  }

  return (
    <group name="425" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh425" position={[14.971, 16.2524, 57.9112]}>
        <mesh
          name="Mesh425"
          geometry={nodes.Mesh425.geometry}
          material={meshMaterial}
          onPointerOver={() => setHovered(true)}
          onPointerOut={() => setHovered(false)}
        />

        {/* 指示牌 */}
        {hovered && <Indicator targetRef={targetRef} name='425' />}
        <BimText3D text="425" width={6} position={[5, 0, 12]} />
        <BimText3D text="425" width={6} position={[12.3, 0, 11]} rotation={[0, Math.PI / 2, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
