/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cube424.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from './Indicator'

export function Cube424(props) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="424" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh424" position={[14.906, 3.15592, 62.43]}>
        <group name="pipe001">
          <group name="Mesh10">
            <mesh name="Mesh009" geometry={nodes.Mesh009.geometry} material={materials.FrontColor} />
            <mesh name="Mesh009_1" geometry={nodes.Mesh009_1.geometry} material={materials.BackColor} />
          </group>
          <group name="Mesh11">
            <mesh name="Mesh010" geometry={nodes.Mesh010.geometry} material={materials.FrontColor} />
            <mesh name="Mesh010_1" geometry={nodes.Mesh010_1.geometry} material={materials.BackColor} />
          </group>
          <group name="Mesh12">
            <mesh name="Mesh011" geometry={nodes.Mesh011.geometry} material={materials.FrontColor} />
            <mesh name="Mesh011_1" geometry={nodes.Mesh011_1.geometry} material={materials.BackColor} />
          </group>
          <group name="Mesh13">
            <mesh name="Mesh012" geometry={nodes.Mesh012.geometry} material={materials.FrontColor} />
            <mesh name="Mesh012_1" geometry={nodes.Mesh012_1.geometry} material={materials.BackColor} />
          </group>
        </group>

        <mesh name="Mesh424" geometry={nodes.Mesh424.geometry} material={materials.Color_M04} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} name='424' />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
