/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jz.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import Indicator from './Indicator'
import { CubeProps } from './type'

type GLTFResult = GLTF & {
  nodes: { [key: string]: THREE.Mesh }
  materials: { [key: string]: THREE.Material }
}

export function Cube507({ ...props }: CubeProps) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb') as GLTFResult
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="507" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh507" position={[14.906, 34.884, -61.16]}>
        <mesh name="Mesh507" geometry={nodes.Mesh507.geometry} material={materials.Color_M05} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} name='507' orientPos={[0,0,-20]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
