/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jz.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from './Indicator'

export function Cube506(props) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="506" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh5061" position={[14.906, 16.088, -62.293]}>
        <mesh name="Mesh5061_1" geometry={nodes.Mesh5061_1.geometry} material={materials.Color_M05} />
        <mesh name="Mesh5061_2" geometry={nodes.Mesh5061_2.geometry} material={materials.BackColor} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} name='506' orientPos={[0,0,-20]} />
      </group>
      <group name="Mesh5062" position={[14.906, 15.722, -49.877]}>
        <mesh name="Mesh5062_1" geometry={nodes.Mesh5062_1.geometry} material={materials.Color_M05} />
        <mesh name="Mesh5062_2" geometry={nodes.Mesh5062_2.geometry} material={materials.BackColor} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
