/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cube580.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from './Indicator'

export function Cube580(props) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="580" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh580" position={[-15.494, 2.647, -19.706]}>
                <mesh name="Mesh580_1" geometry={nodes.Mesh580_1.geometry} material={materials.Color_M04} />
                <mesh name="Mesh580_2" geometry={nodes.Mesh580_2.geometry} material={materials.BackColor} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} name='580' />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
