/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cube419.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from './Indicator'
import { CubeProps } from './type'

export function Cube417({ ...props }: CubeProps) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="417" {...props} dispose={null}>
      {/* <group name="Mesh419" position={[-15.494, 33.843, 61.451]}> */}
      <group ref={targetRef} name="Mesh417" position={[-15.4939, 3.15592, 62.43]}>
        <mesh name="Mesh417" geometry={nodes.Mesh417.geometry} material={materials.Color_M05} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} name='417' />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
