/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jz.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from './Indicator'
import { CubeProps } from './type'

export function Cube587({ ...props }: CubeProps) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="587" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh587" position={[14.906, 14.964, -19.706]}>
        <mesh name="Mesh587_1" geometry={nodes.Mesh587_1.geometry} material={materials.Color_M04} />
        <mesh name="Mesh587_2" geometry={nodes.Mesh587_2.geometry} material={materials.BackColor} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} name='587' orientPos={[20,0,0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
