/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cube426.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from './Indicator'
import { CubeProps } from './type'

export function Cube426({ ...props }: CubeProps) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="426" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh426" position={[14.9061, 33.7707, 61.7309]}>
        <mesh name="Mesh426_1" geometry={nodes.Mesh426_1.geometry} material={materials.Color_M05} />
        <mesh name="Mesh426_2" geometry={nodes.Mesh426_2.geometry} material={materials.BackColor} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} name='426' />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
