/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jz.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from './Indicator'

export function Cube498(props) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="498" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh498" position={[-15.494, 3.156, -61.843]}>
        <mesh name="Mesh498" geometry={nodes.Mesh498.geometry} material={materials.Color_M00} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} name='498' orientPos={[0,0,-20]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
