/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cube578.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from './Indicator'

export function Cube578(props) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="578" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh578" position={[-15.494, 14.964, 20.294]}>
        <mesh name="Mesh578_1" geometry={nodes.Mesh578_1.geometry} material={materials.Color_M04} />
        <mesh name="Mesh578_2" geometry={nodes.Mesh578_2.geometry} material={materials.BackColor} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} name='578' />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
