/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jz.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from './Indicator'
import { CubeProps } from './type'

export function Cube586({ ...props }: CubeProps) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="586" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh586" position={[14.906, 2.647, -19.706]}>
        <mesh name="Mesh586_1" geometry={nodes.Mesh586_1.geometry} material={materials.Color_M00} />
        <mesh name="Mesh586_2" geometry={nodes.Mesh586_2.geometry} material={materials.BackColor} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} name='586' orientPos={[20,0,0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
