/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jz.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Indicator from './Indicator'
import { CubeProps } from './type'

export function Cube500({ ...props }: CubeProps) {
  const { nodes, materials } = useGLTF('/assets/model/hhiot/jz.glb')
  const targetRef = useRef<THREE.Group>(null!)

  return (
    <group name="500" {...props} dispose={null}>
      <group ref={targetRef} name="Mesh500" position={[-15.494, 34.884, -61.16]}>
        <mesh name="Mesh500" geometry={nodes.Mesh500.geometry} material={materials['Color_M05.001']} />

        {/* 指示牌 */}
        <Indicator targetRef={targetRef} name='500' orientPos={[0,0,-20]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/hhiot/jz.glb')
