/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bbb.01.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Elec220v(props) {
  const { nodes, materials } = useGLTF('/assets/model/elec220v.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['220kV_01'].geometry} material={materials['02___Default']} position={[9.831, 0, 0.903]} rotation={[Math.PI / 2, 0, 0]} scale={0.048} />
      <mesh geometry={nodes['220kV_02'].geometry} material={materials.豸} position={[9.831, 0, 0.903]} rotation={[Math.PI / 2, 0, 0]} scale={0.048} />
      <mesh geometry={nodes['220kV_03'].geometry} material={materials.wire_135006006} position={[9.831, 0, 0.903]} rotation={[Math.PI / 2, 0, 0]} scale={0.048} />
      <mesh geometry={nodes.Box001.geometry} material={materials['01___Default']} position={[9.831, 0, 0.903]} rotation={[Math.PI / 2, 0, 0]} scale={0.048} />
    </group>
  )
}

useGLTF.preload('/assets/model/elec220v.glb')
