/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 aaa.01.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function House02(props) {
  const { nodes, materials } = useGLTF('/assets/model/house.02.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-38.95, 0, 2.749]} rotation={[Math.PI / 2, 0, 0]} scale={0}>
        <mesh geometry={nodes['20221025小岛组团_V8_1'].geometry} material={materials._0135_DarkGray_1} />
        <mesh geometry={nodes['20221025小岛组团_V8_2'].geometry} material={materials._0135_DarkGray_5} />
        <mesh geometry={nodes['20221025小岛组团_V8_3'].geometry} material={materials.___glass} />
        <mesh geometry={nodes['20221025小岛组团_V8_4'].geometry} material={materials._Slate_Light_Tile_1} />
        <mesh geometry={nodes['20221025小岛组团_V8_5'].geometry} material={materials.TL1} />
        <mesh geometry={nodes['20221025小岛组团_V8_6'].geometry} material={materials._21} />
        <mesh geometry={nodes['20221025小岛组团_V8_7'].geometry} material={materials.TL2} />
        <mesh geometry={nodes['20221025小岛组团_V8_8'].geometry} material={materials._2} />
        <mesh geometry={nodes['20221025小岛组团_V8_9'].geometry} material={materials.Material__2147476640} />
        <mesh geometry={nodes['20221025小岛组团_V8_10'].geometry} material={materials.Color_M06} />
        <mesh geometry={nodes['20221025小岛组团_V8_11'].geometry} material={materials.Material__2147476639} />
        <mesh geometry={nodes['20221025小岛组团_V8_12'].geometry} material={materials.Color_C08} />
        <mesh geometry={nodes['20221025小岛组团_V8_13'].geometry} material={materials.Blacktop_Old_01} />
        <mesh geometry={nodes['20221025小岛组团_V8_14'].geometry} material={materials._0129_WhiteSmoke_2} />
        <mesh geometry={nodes['20221025小岛组团_V8_15'].geometry} material={materials._5} />
        <mesh geometry={nodes['20221025小岛组团_V8_16'].geometry} material={materials.js1} />
        <mesh geometry={nodes['20221025小岛组团_V8_17'].geometry} material={materials._Color_M00_1} />
        <mesh geometry={nodes['20221025小岛组团_V8_18'].geometry} material={materials.Cladding_Siding_White} />
        <mesh geometry={nodes['20221025小岛组团_V8_19'].geometry} material={materials.Groundcover_Sand_Raked} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/house.02.glb')
